name: Deploy to Kubernetes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy-to-main:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      
      - name: Set Tag as Environment Variable
        run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Build Docker image and push it to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ${DOCKER_USERNAME}/market-news-main:${{ env.IMAGE_TAG }} -f Dockerfile-main .
          docker push ${DOCKER_USERNAME}/market-news-main:${{ env.IMAGE_TAG }}

      - name: Get Latest Image Tag
        id: extract_tag
        run: |
          TAG=$(docker images --format "{{.Tag}}" bdtask/market-news-main:${{ env.IMAGE_TAG }})
          echo "::set-output name=tag::$TAG"

      - name: Update Deployment File
        run: |
          sed -i 's|image: bdtask/market-news-staging:.*|image: bdtask/market-news-staging:${{ steps.extract_tag.outputs.tag }}|g' k8s/deployment.yaml

        
      - name: Commit files
        run: |
          git config --local user.email "survivalmotivator@gmail.com"
          git config --local user.name "awscloude"
          git commit -am "rolling image to tag $GITHUB_SHA"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.0'

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          cd k8s
          kubectl apply -f deployment.yaml
